apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
        - name: timescaledb
          image: timescale/timescaledb:latest-pg18
          env:
            - name: POSTGRES_PASSWORD
              value: "iicpc"
            - name: POSTGRES_DB
              value: "iicpc"
          ports:
            - name: postgres
              containerPort: 5432
          resources:
            requests:
              memory: 256Mi
              cpu: "250m"
            limits:
              memory: 512Mi
              cpu: "500m"
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: timescaledb-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescaledb-data
  namespace: platform
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  namespace: platform
spec:
  selector:
    app: timescaledb
  ports:
    - name: postgres
      port: 5432
