apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: telemetry-ingester
  namespace: platform
  labels:
    {{- include "obarena.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: telemetry-ingester
    kind: Deployment
    apiVersion: apps/v1
  pollingInterval: {{ .Values.kedaScaling.pollingInterval }}
  cooldownPeriod: {{ .Values.kedaScaling.cooldownPeriod }}
  minReplicaCount: {{ .Values.kedaScaling.telemetryIngester.minReplicas }}
  maxReplicaCount: {{ .Values.kedaScaling.telemetryIngester.maxReplicas }}
  advanced:
    restoreToOriginalReplicaCount: true
  triggers:
    - type: apache-kafka
      metadata:
        bootstrapServers: redpanda.platform.svc.cluster.local:9092
        consumerGroup: {{ .Values.kedaScaling.telemetryIngester.consumerGroup }}
        topic: {{ .Values.kedaScaling.telemetryIngester.topic }}
        lagThreshold: {{ .Values.kedaScaling.telemetryIngester.lagThreshold | quote }}
        allowIdleConsumers: "false"
        offsetResetPolicy: latest
