apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescaledb-data
  namespace: platform
  labels:
    {{- include "obarena.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- $sc := .Values.storage.timescaledbStorageClass | default .Values.storage.className }}
  {{- if $sc }}
  storageClassName: {{ $sc | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.timescaledb.size }}
