apiVersion: v1
kind: Secret
metadata:
  name: iicpc-timescaledb
  namespace: platform
  labels:
    {{- include "iicpc.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.timescaledb.password | b64enc | quote }}
  dsn: {{ printf "postgres://postgres:%s@timescaledb.platform.svc.cluster.local:5432/postgres?sslmode=disable" .Values.timescaledb.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: iicpc-redis
  namespace: platform
  labels:
    {{- include "iicpc.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.redis.password | b64enc | quote }}
